puns = ["The dog is so popular that the pup-arazzi took its photo.",
"It’s raining cats and dogs. That’s fine, as long as it doesn’t reindeer.",
"Pavlov? He rings a bell.",
"Have you heard about the new dog movie? It’s called Jurassic Bark.",
"Take the dog for a walk. That’s the leashed you could do.",
"Feeling down? Maybe this dog can cheer you up.",
"My dog’s favorite band is The Beagles.",
"What does the dog eat at the movies? Pup-peroni pizza and pupcorn!",
"Where do dogs go after their tails fall off? The re-tail store.",
"Howl I ever live without you?",
"You have the corg-key to my heart.",
"What dog does Dracula own? A bloodhound.",
"What happened to the dog who gave birth on the side of the road? She was ticketed for littering!",
"My friend said he once threw a stick two miles and his dog still brought it back… Seems a bit far-fetched to me!",
"What's my dog's favorite movie? Harry Paw-ter and the Sorcerer's Bone!",
"What's better than a spelling bee? A talking dog!",
"Where do dogs like to surf? Colliefornia!",
"What's a dog's favorite activity to do in school? Lab reports!",
"The Dachshund had to sit in the shade because it was a hot dog.",
"How do you know a good dog pun from a bad dog pun? The good ones make you bark with laughter!",
"The dog couldn't remember where he parked his car in the barking lot.",
"Where do dogs like to surf? Colliefornia!",
"What do you call a cold dog? A pupsicle.",
"Did you see the dog's new outfit? It was quite fetching.",
"He's a bad dog; he;s just a little ruff around the edges.",
]